feat: navbar-scroll
bangmod-hackathon/bmhk2024-2 pull request #39
Opened 2024-07-29 11:00 UTC by SSSBoOm

2024-07-29 11:26 UTC, sokungz01 requested changes
Please implement smooth scroll for mobile.

2024-07-29 11:30 UTC, ChaiyapatOam commented
Does it has cursor-pointer?

2024-07-30 12:27 UTC, sokungz01 approved these changes

2024-07-30 12:27 UTC, sokungz01 commented
LGTM ✨

2024-07-30 12:28 UTC, merged