Feat(Timeline) - Waviez Edition
bangmod-hackathon/bmhk2024-2 pull request #40
Opened 2024-07-29 11:52 UTC by Pongpon00

### Changelog
- Add new Timeline feature with a progress bar.
- Update App.tsx for testing
- Upload new assets

2024-07-29 12:10 UTC, sokungz01 commented
Can you fix this white box on the mobile?

<img width="1440" alt="Screenshot 2567-07-29 at 19 08 48" src="https://github.com/user-attachments/assets/3e1a0fd6-4de2-4885-a31e-343f3419719c">

2024-07-29 12:10 UTC, Pongpon00 commented
ok pap

2024-07-29 12:44 UTC, sokungz01 requested changes

2024-07-29 12:44 UTC, sokungz01 commented on public/LandingBackground.jpg
Can you convert the image files (jpg/png) to webp file?
These image files will cause the website load time.

2024-07-30 02:59 UTC, Pongpon00 commented
I already fix the responsive design
![timeline responsive design](https://github.com/user-attachments/assets/3be4bb62-f3ef-4b1f-8aa0-2e3080014b0f)

2024-07-30 03:06 UTC, Pongpon00 commented on public/LandingBackground.jpg
I tried to convert the jpg image to webp image but it doesn't reduce the file size. Instead, the file size is bigger.  

![image](https://github.com/user-attachments/assets/f489efce-2b98-4724-9c4f-d8210d665f0c)

2024-07-30 03:07 UTC, Pongpon00 commented on public/LandingBackground.jpg
do you have any suggest?

2024-07-30 03:11 UTC, sokungz01 commented on public/LandingBackground.jpg
Can you ask @SSSBoOm ?

2024-07-30 03:17 UTC, Pongpon00 commented on public/LandingBackground.jpg
Ok

2024-07-30 09:11 UTC, Pongpon00 commented on public/LandingBackground.jpg
Problem resolved!

2024-07-30 12:29 UTC, sokungz01 commented
LGTM ✨

2024-07-30 12:30 UTC, sokungz01 commented
@Pongpon00 Can you resolve a conflict, please?

2024-07-30 12:44 UTC, sokungz01 commented
> @Pongpon00 Can you resolve a conflict, please?

lmk, if you solved a conflict

2024-07-30 13:04 UTC, Pongpon00 commented
Ok, Got it.

2024-07-30 13:16 UTC, merged