Feat(registration form template)
bangmod-hackathon/bmhk2024-2 pull request #41
Opened 2024-07-29 12:39 UTC by SupeemAFK

- Change **Input** component from AntDesign to Custom
- Create **Select**, **Option**, **TextArea** component
- Create Form Template Component (ข้อมูลทีม, ข้อมูลอาจารย์, ข้อมูลติดต่ออาจารย์, ข้อมูลสมาชิก, ข้อมูลติดต่อสมาชิก)

2024-07-29 13:11 UTC, sokungz01 requested changes

2024-07-29 13:11 UTC, sokungz01 commented on src/components/Form/Input/Input.tsx
> +        className={`rounded-[5px] bg-white px-3 py-2 ${props.error ? 'border-2 border-red-500 text-red-500' : 'border-2 border-white text-primary-100'} focus:shadow-[0_4px_6px_0px_rgba(138,213,244,0.
Can you check `rounded-[size]` for all input types on figma? 
I think it isn't correct

2024-07-29 13:11 UTC, sokungz01 commented on src/components/Form/Input/Input.tsx
> +        {props.title} {props.required && <span className="text-primary_yellow-100">*</span>}
For the input label, I think `text-color` doesn't match on the Figma.
Can you check it for me?

2024-07-29 13:11 UTC, sokungz01 commented on src/components/Form/Input/Select.tsx
> +      <select className="px-3 py-2 rounded-[5px] border-2 border-white  text-[#999999] focus:text-primary-100 focus:shadow-[0_4px_6px_0px_rgba(138,213,244,0.25)] focus:outline-none focus:ring-2 focus
Is it possible for implement select options from the design system?
If possible we can create a new task for that.

2024-07-29 13:13 UTC, sokungz01 commented
Can you explain why we need to change from `antd form` to `custom form`?

2024-07-29 14:55 UTC, SupeemAFK commented on src/components/Form/Input/Input.tsx
> +        className={`rounded-[5px] bg-white px-3 py-2 ${props.error ? 'border-2 border-red-500 text-red-500' : 'border-2 border-white text-primary-100'} focus:shadow-[0_4px_6px_0px_rgba(138,213,244,0.
okay the correct radius is 10px I'll fix that

2024-07-29 14:57 UTC, SupeemAFK commented on src/components/Form/Input/Input.tsx
> +        {props.title} {props.required && <span className="text-primary_yellow-100">*</span>}
I'm confuse with the input there 3 styles what should bg-color and text-color be on both default and hover

![image](https://github.com/user-attachments/assets/ff9cd683-3a65-4669-a9a8-4e3cd84a5a37)

2024-07-29 15:04 UTC, SupeemAFK commented
I just think custom form is more customizable than antd so I just use it but if you want antd form instead of custom form I can change that

2024-07-29 15:27 UTC, SupeemAFK commented on src/components/Form/Input/Input.tsx
> +        {props.title} {props.required && <span className="text-primary_yellow-100">*</span>}
bg should be white and text color shound be primary-200 right?

2024-07-29 16:54 UTC, SupeemAFK commented on src/components/Form/Input/Select.tsx
> +      <select className="px-3 py-2 rounded-[5px] border-2 border-white  text-[#999999] focus:text-primary-100 focus:shadow-[0_4px_6px_0px_rgba(138,213,244,0.25)] focus:outline-none focus:ring-2 focus
I try changing select and option style base on Figma but no luck look like we have to implement our select component instead of using <select> and <option> html tag

2024-07-29 16:54 UTC, SupeemAFK commented on src/components/Form/Input/Input.tsx
> +        className={`rounded-[5px] bg-white px-3 py-2 ${props.error ? 'border-2 border-red-500 text-red-500' : 'border-2 border-white text-primary-100'} focus:shadow-[0_4px_6px_0px_rgba(138,213,244,0.
fix to 10px

2024-07-29 16:56 UTC, SupeemAFK commented on src/components/Form/Input/Input.tsx
> +        {props.title} {props.required && <span className="text-primary_yellow-100">*</span>}
fix text-color to text-primary-200

2024-07-29 17:09 UTC, sokungz01 commented on src/components/Form/Input/Select.tsx
> +      <select className="px-3 py-2 rounded-[5px] border-2 border-white  text-[#999999] focus:text-primary-100 focus:shadow-[0_4px_6px_0px_rgba(138,213,244,0.25)] focus:outline-none focus:ring-2 focus
Okay, I see

2024-07-29 17:14 UTC, sokungz01 commented
@SSSBoOm Can you help me to review this PR, please? I have a company work so I think I cannot too much focus on this.

- Can we use `useForm` from antd to the control our custom input form component instead of `antd components`?

2024-07-30 12:34 UTC, sokungz01 commented on src/components/Form/Input/Input.tsx
> +        className={`rounded-[5px] bg-white px-3 py-2 ${props.error ? 'border-2 border-red-500 text-red-500' : 'border-2 border-white text-primary-100'} focus:shadow-[0_4px_6px_0px_rgba(138,213,244,0.
Do you fix it?

2024-07-30 12:39 UTC, SupeemAFK commented on src/components/Form/Input/Input.tsx
> +        className={`rounded-[5px] bg-white px-3 py-2 ${props.error ? 'border-2 border-red-500 text-red-500' : 'border-2 border-white text-primary-100'} focus:shadow-[0_4px_6px_0px_rgba(138,213,244,0.
yeah I fixed it

2024-07-30 12:41 UTC, sokungz01 approved these changes

2024-07-30 12:47 UTC, SupeemAFK commented
Do I have to wait @SSSBoOm to review my PR before I merge.

2024-07-30 12:49 UTC, sokungz01 commented
Yeah, I think we should wait @SSSBoOm to conclude about form components.

2024-07-30 14:19 UTC, sokungz01 commented
> Do I have to wait @SSSBoOm to review my PR before I merge.

I've talked with @SSSBoOm so, he prefer to used `antd form` components.
Can you implement for the antd form components?

2024-07-30 14:45 UTC, SupeemAFK commented
okay

2024-07-30 15:11 UTC, SupeemAFK commented
Look like if I use antd Form the style is broken. The layout, padding, flex box everything about layout style is broken

2024-07-30 15:35 UTC, sokungz01 commented
> Look like if I use antd Form.Item the style is broken. The layout, padding, flex box everything about layout style is broken

Do you need some help for helping about layout/style ?

2024-07-30 15:45 UTC, SupeemAFK commented
yeah can you help me migrate to antd Form

2024-08-01 04:02 UTC, sokungz01 commented
Can you change other form to using `Form.Item` for me, @SupeemAFK  please? 
Don't focus on styling, I'll take care of this part after this.

2024-08-01 05:53 UTC, SupeemAFK commented
ok got it

2024-08-01 07:01 UTC, sokungz01 commented
lmk if you faced some problems

2024-08-01 07:38 UTC, SupeemAFK commented
What about placeholder? Will you take care of it?

2024-08-01 07:43 UTC, sokungz01 commented
Just add all placeholder for all input components but for the styling I will take care all of these.

2024-08-01 09:32 UTC, SupeemAFK commented
Change to antd form completed.

2024-08-01 10:52 UTC, sokungz01 commented
Example form:

<img width="1680" alt="Screenshot 2567-08-01 at 17 51 51" src="https://github.com/user-attachments/assets/a3789632-acc2-4569-a59f-97cf4cb3b9e5">

2024-08-01 10:54 UTC, sokungz01 commented
I will re-styling some gap between form components

2024-08-01 10:54 UTC, merged